[project]
name = "py-demos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "arosics>=1.13.2",
    "earthengine-api>=1.7.26",
    "geopandas>=1.1.3",
    "numpy>=2.4.6",
    "pystac-client>=0.9.0",
    "rasterio>=1.5.0",
    "scikit-learn>=1.8.0",
    "tqdm>=4.67.3",
    "yaspin>=3.4.0",
]
